# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon 
from PyQt5.QtWidgets import QInputDialog, QLineEdit, QMessageBox,       QWidget, QListWidgetItem   # ++

                                                                            # - object  + QWidget




class Ui_Dialog(QWidget):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(708, 452)
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 10, 701, 421))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_add = QtWidgets.QPushButton(self.widget)
        self.pushButton_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout.addWidget(self.pushButton_add)
        self.pushButton_edit = QtWidgets.QPushButton(self.widget)
        self.pushButton_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.verticalLayout.addWidget(self.pushButton_edit)
        self.pushButton_remover = QtWidgets.QPushButton(self.widget)
        self.pushButton_remover.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_remover.setObjectName("pushButton_remover")
        self.verticalLayout.addWidget(self.pushButton_remover)
        self.pushButton_up = QtWidgets.QPushButton(self.widget)
        self.pushButton_up.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_up.setObjectName("pushButton_up")
        self.verticalLayout.addWidget(self.pushButton_up)
        self.pushButton_down = QtWidgets.QPushButton(self.widget)
        self.pushButton_down.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_down.setObjectName("pushButton_down")
        self.verticalLayout.addWidget(self.pushButton_down)
        self.pushButton_confirmar = QtWidgets.QPushButton(self.widget)
        self.pushButton_confirmar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_confirmar.setObjectName("pushButton_confirmar")
        self.verticalLayout.addWidget(self.pushButton_confirmar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_sair = QtWidgets.QPushButton(self.widget)
        self.pushButton_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_sair.setObjectName("pushButton_sair")
        self.verticalLayout.addWidget(self.pushButton_sair)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        #Dialog.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Dialog)
        self.statusbar.setObjectName("statusbar")
        #Dialog.setStatusBar(self.statusbar)

        self.pushButton_add.clicked.connect(self.Add)
        self.pushButton_edit.clicked.connect(self.Edit)
        self.pushButton_remover.clicked.connect(self.Remove)
        self.pushButton_up.clicked.connect(self.Up)
        self.pushButton_down.clicked.connect(self.Down)
        self.pushButton_confirmar.clicked.connect(self.Sort)
        self.pushButton_sair.clicked.connect(self.Close)
        
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.Employee()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Colaboradores App: "))
        Dialog.setWindowIcon(QIcon("proj_logo.jpg"))
        self.pushButton_add.setText(_translate("Dialog", "Add"))
        self.pushButton_edit.setText(_translate("Dialog", "Editar"))
        self.pushButton_remover.setText(_translate("Dialog", "Remover"))
        self.pushButton_up.setText(_translate("Dialog", "Up"))
        self.pushButton_down.setText(_translate("Dialog", "Down"))
        self.pushButton_confirmar.setText(_translate("Dialog", "Confirmar"))
        self.pushButton_sair.setText(_translate("Dialog", "Sair"))
        self.label.setText(_translate("Dialog", "<html><body>< align=\"center\"><span style=\"font-size: 8pt; color:#0000ff;\">joanescaraujo@gmail.com | Todos os direitos reservados.!</span></body></html>"))

        

    def Employee(self):
        self.employee = ["Joanes","Pablo", "Marcos", "Luiz", "Christiane"]
        self.listWidget.addItems(self.employee)
        self.listWidget.setCurrentRow(0)

    def Add(self):
        row = self.listWidget.currentRow()
        text, ok = QInputDialog.getText(self, "CADASTRO DO FUNCIONARIO", "DIGITE O NOME DO FUNCIONARIO")
        if ok and text is not None:
            self.listWidget.insertItem(row, text)

    def Edit(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)
        string, ok = QInputDialog.getText(self, "CADASTRO DO FUNCIONARIO", "EDITE O NOME DO FUNCIONARIO",QLineEdit.Normal,item.text())
        if ok and string is not None:
            item.setText(string)

    def Remove(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)
        if item is None:
            return

        reply = QMessageBox.question(self,"DELETAR ESSE FUNCIONARIO?", "DESEJA REALMENTE REMOVER ESSE FUNCIONARIO?!" + str(item.text()),
                QMessageBox.Yes| QMessageBox.No)

        if reply == QMessageBox.Yes:
            item = self.listWidget.takeItem(row)
            del item
            reply = QMessageBox.information(self, "joanescaraujo@gmail.com", "FUNCIONARIO DELETADO COM SUCESSO")


    def Up(self):
        row = self.listWidget.currentRow()
        if row>=1:
            item = self.listWidget.takeItem(row)
            self.listWidget.insertItem(row-1,item)
            self.listWidget.setCurrentItem(item)

    def Down(self):
        row = self.listWidget.currentRow()
        if row< self.listWidget.count() -1:
            item = self.listWidget.takeItem(row)
            self.listWidget.insertItem(row+1,item)
            self.listWidget.setCurrentItem(item)

    def Sort(self):
        self.listWidget.sortItems()

    def Close(self):
        quit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
